# See https://pre-commit.com/ for usage and config
repos:
  - repo: local
    hooks:
      - id: dprint
        name: dprint
        entry: dprint fmt --incremental=false --allow-no-files
        language: node
        pass_filenames: false
        additional_dependencies: [dprint]
