# Generated form root with
# d2 --force-appendix --dark-theme 200 --theme 200 --watch --sketch content/attachments/egu.d2 out.svg

title: Insensitivity of global temperature \nresponse to the magnitude of \nvolcanic eruptions
title.shape: cloud

view: Overarching questinos and results {
  q1: |md
    - Show the temperature response to volcanoes of different magnitude.
      - But what should define magnitude?
      - Over what range is there a linear relation?
  |
  q2: |md
    - More pure volcanic simulations to diagnose the climate response
      - Both with AOGCMs and AGCMs
      - Does other models exibit a cloud adjustment?
  |
  q3: |md
    - Events superpose
      - At least our very early results point in that direction
  |
}

motivation: Motivation {
  plt: "AOD vs TOA from Gregory et al. (2016)" {
    formula: |md
    - People have looked into it up to AOD=0.15
    |
  }
  quote: '"Run with both AOGCMs and AGCMs"'
  linearity_formula: "Linearity relation" {
    formula: |latex
      T = L\[F\]
    |
  }
  alternatives: SO2, AOD, TOA, or some function of them?

  plt -> quote -> linearity_formula -> alternatives
}

results: Results {
  aodtmp: AOD vs temperature
  toatmp: TOA vs temperature
  so2tmp: SO2 vs temperature

  aodtmp <-> toatmp <-> so2tmp <-> aodtmp: Compare them?
}

view.q1 -> motivation.plt
view.q1 -> motivation.linearity_formula
view.q2 -> motivation.quote
view.q3 -> motivation.linearity_formula
view.q3 -> motivation.alternatives

# title -> motivation: To start it off
# title -> results: Makes sense of the title
motivation.plt <-> results: Compare these as well?
